language: php
sudo: required
dist: trusty
group: edge

matrix:
  include:
    - php: 7.1
      env:
        - SEND_COVERAGE=true
    - php: 7.2
  allow_failures:
    # PHP7.2 failure is due to php-code-fixer
    # can safely be removed when updated to 7.2
    - php: 7.2


before_script:
  - composer install
  - mysql -e "DROP DATABASE IF EXISTS openstore_test_utf8_compat;" -u root
  - mysql -e "CREATE DATABASE openstore_test_utf8_compat;" -u root
  - cp ./.travis/openstore-schema-core.config.travis.php ./config/openstore-schema-core.config.php
script:
  - composer build
  - cat resources/sql/mysql-utf8-compat/create_schema_utf8_compat.sql | mysql -u root openstore_test_utf8_compat
  - cat resources/sql/mysql-utf8-compat/create_extra_utf8_compat.sql | mysql -u root openstore_test_utf8_compat
  - ./bin/openstore-schema-core openstore:schema:create --dump-sql
  - ./vendor/bin/php-cs-fixer --diff --dry-run -v fix

