language: php
sudo: required
dist: bionic

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

before_script:
  - if [[ "$SET_INNODB_CONF" == "yes" ]]; then echo -e "[server]\ninnodb_file_per_table=1\ninnodb_file_format=barracuda\ninnodb_large_prefix=1" | sudo tee -a /etc/mysql/my.cnf; sudo service mysql restart; fi;
  # Create two test databases
  - mysql -e "DROP DATABASE IF EXISTS openstore_test_utf8_compat;" -u root
  - mysql -e "CREATE DATABASE openstore_test_utf8_compat;" -u root
  - mysql -e "DROP DATABASE IF EXISTS openstore_test_utf8mb4;" -u root
  - mysql -e "CREATE DATABASE openstore_test_utf8mb4;" -u root
  - cp ./.travis/openstore-schema-core.config.travis.php ./config/openstore-schema-core.config.php

install:
  - travis_retry composer -n install

script:
  # Test 1.
  # Build generated SQL and check they work by pushing them to the db
  - composer build
  # - Create a database from generated SQL (utf8)
  - cat resources/sql/mysql-utf8-compat/create_schema_utf8_compat.sql | mysql -u root openstore_test_utf8_compat
  - cat resources/sql/mysql-utf8-compat/create_schema_extra_utf8_compat.sql | mysql -u root openstore_test_utf8_compat
  - cat resources/sql/mysql-utf8-compat/create_schema_extra_utf8_compat.sql
  # - Create a database from generated SQL (utf8mb4)
  - cat resources/sql/create_schema_utf8mb4.sql | mysql -u root openstore_test_utf8mb4
  - cat resources/sql/create_schema_extra_utf8mb4.sql | mysql -u root openstore_test_utf8mb4
  - cat resources/sql/create_schema_extra_utf8mb4.sql
  # Running a diff should not generate migrations (--dump-sql for debug it always return 0 exit code)
  - php vendor/bin/doctrine orm:schema-tool:update --dump-sql
  - php vendor/bin/doctrine orm:schema-tool:update

  # Test 2.
  # Recreate test database from doctrine
  - mysql -e "DROP DATABASE IF EXISTS openstore_test_utf8mb4;" -u root
  - mysql -e "CREATE DATABASE openstore_test_utf8mb4;" -u root
  - php vendor/bin/doctrine orm:schema-tool:create
  # Running a diff should not generate migrations (--dump-sql for debug it always return 0 exit code)
  - php vendor/bin/doctrine orm:schema-tool:update --dump-sql
  - php vendor/bin/doctrine orm:schema-tool:update
  # Test 3.
  # Adding a new entity should generate a new diff
  - cp tests/entity/Question.php src/OpenstoreSchema/Core/Entity/Question.php
  - php vendor/bin/doctrine orm:schema-tool:update --dump-sql
  # Updating schema
  - php vendor/bin/doctrine orm:schema-tool:update --force
  # This one should not give new migrations (--dump-sql for debug it always return 0 exit code)
  - php vendor/bin/doctrine orm:schema-tool:update --dump-sql
  - php vendor/bin/doctrine orm:schema-tool:update

jobs:
  include:
    # PHPStan - CS
    - stage: PHPStan
      php: 7.3
      env: MARIADB_VERSION=10.3 SET_INNODB_CONF=no
      addons:
        mariadb: 10.3
      script:
        - composer phpstan
        - ./vendor/bin/php-cs-fixer --diff --dry-run -v fix

    # PHP 7.2
    - stage: Test
      php: 7.2
      env: MYSQL_VERSION=5.7 SET_INNODB_CONF=yes
      sudo: required
    - stage: Test
      php: 7.2
      env: MARIADB_VERSION=10.1 SET_INNODB_CONF=yes
      addons:
        mariadb: 10.1
    - stage: Test
      php: 7.2
      env: MARIADB_VERSION=10.2 SET_INNODB_CONF=yes
      addons:
        mariadb: 10.2
    # PHP 7.3
    - stage: Test
      php: 7.3
      env: MYSQL_VERSION=5.7 SET_INNODB_CONF=yes
      sudo: required
    - stage: Test
      php: 7.3
      env: MARIADB_VERSION=10.1 SET_INNODB_CONF=yes
      addons:
        mariadb: 10.1
    - stage: Test
      php: 7.3
      env: MARIADB_VERSION=10.2 SET_INNODB_CONF=yes
      addons:
        mariadb: 10.2
    - stage: Test
      php: 7.3
      env: MARIADB_VERSION=10.3 SET_INNODB_CONF=no
      addons:
        mariadb: 10.3
    - stage: Test
      php: 7.3
      env: MARIADB_VERSION=10.4 SET_INNODB_CONF=no
      addons:
        mariadb: 10.4




